//! Independently assembled native FULL transaction-hash preimage for A1 v1.
//!
//! Specification source inspected: rusty-kaspa 01b532e8b553523216471682649693af92f0fd16,
//! consensus/core/src/hashing/tx.rs (`write_transaction`, FULL), and hashing/mod.rs
//! (`write_len`: LE64). This does not invoke the upstream transaction serializer
//! or hashing::tx::write_transaction. It is the bytes committed by TransactionHash,
//! not Borsh object bytes, a protobuf/network envelope, or the mass-size estimate.
//! In this encoding SPK version is LE16, unlike A1 context/introspection BE16.

use kaspa_consensus_core::tx::Transaction;
use kaspa_hashes::{Hash, HasherBase, TransactionHash};

fn length(out: &mut Vec<u8>, value: usize) -> Result<(), String> {
    out.extend(
        u64::try_from(value)
            .map_err(|_| "length exceeds native u64")?
            .to_le_bytes(),
    );
    Ok(())
}

fn variable_bytes(out: &mut Vec<u8>, value: &[u8]) -> Result<(), String> {
    length(out, value.len())?;
    out.extend(value);
    Ok(())
}

/// Strictly scoped to A1 version 1 and native ComputeBudget input representation.
/// Incorrect compute-commit representation rejects rather than applying upstream
/// hashing's diagnostic default-to-zero behavior to a malformed adapter object.
pub fn full_transaction_bytes(tx: &Transaction) -> Result<Vec<u8>, String> {
    if tx.version != 1 {
        return Err("A1 FULL encoding requires transaction version 1".into());
    }
    let mut out = Vec::new();
    out.extend(tx.version.to_le_bytes());
    length(&mut out, tx.inputs.len())?;
    for input in &tx.inputs {
        out.extend(input.previous_outpoint.transaction_id.as_bytes());
        out.extend(input.previous_outpoint.index.to_le_bytes());
        variable_bytes(&mut out, &input.signature_script)?;
        out.extend(input.sequence.to_le_bytes());
        let budget = input
            .compute_commit
            .compute_budget()
            .ok_or("version 1 input lacks ComputeBudget representation")?;
        out.extend(budget.to_le_bytes());
    }
    length(&mut out, tx.outputs.len())?;
    for output in &tx.outputs {
        out.extend(output.value.to_le_bytes());
        out.extend(output.script_public_key.version().to_le_bytes());
        variable_bytes(&mut out, output.script_public_key.script())?;
        match output.covenant {
            None => out.push(0),
            Some(binding) => {
                out.push(1);
                out.extend(binding.authorizing_input.to_le_bytes());
                out.extend(binding.covenant_id.as_bytes());
            }
        }
    }
    out.extend(tx.lock_time.to_le_bytes());
    let subnetwork: &[u8] = tx.subnetwork_id.as_ref();
    out.extend_from_slice(subnetwork);
    out.extend(tx.gas.to_le_bytes());
    variable_bytes(&mut out, &tx.payload)?;
    // Mandatory for version 1 even when zero: omitting it creates a different hash.
    out.extend(tx.storage_mass().to_le_bytes());
    Ok(out)
}

/// TransactionHash is native BLAKE2b-256 keyed with ASCII "TransactionHash".
/// Reuse that established hash implementation; independently encode its message.
pub fn full_transaction_hash(tx: &Transaction) -> Result<Hash, String> {
    let bytes = full_transaction_bytes(tx)?;
    let mut hasher = TransactionHash::new();
    hasher.update(bytes);
    Ok(hasher.finalize())
}

#[cfg(test)]
mod tests {
    use super::*;
    use kaspa_consensus_core::{
        hashing,
        mass::ComputeBudget,
        subnets::SubnetworkId,
        tx::{
            CovenantBinding, ScriptPublicKey, TransactionInput, TransactionOutpoint,
            TransactionOutput,
        },
    };

    fn sample() -> Transaction {
        let mut output = TransactionOutput::new(
            0x0807060504030201,
            ScriptPublicKey::from_vec(0x0201, vec![0xac, 0x51]),
        );
        output.covenant = Some(CovenantBinding::new(0x0403, Hash::from_bytes([0xbb; 32])));
        let tx = Transaction::new(
            1,
            vec![TransactionInput::new_with_compute_budget(
                TransactionOutpoint::new(Hash::from_bytes([0xaa; 32]), 0x04030201),
                vec![0x01, 0x42],
                0x0807060504030201,
                0x0201,
            )],
            vec![output],
            0x1817161514131211,
            SubnetworkId::from_bytes([0xcc; 20]),
            0x2827262524232221,
            vec![0xdd, 0xee],
        );
        tx.set_storage_mass(0x3837363534333231);
        tx
    }

    #[test]
    fn literal_full_v1_byte_vector_matches_independent_encoding() {
        // Manually transcribed fields, not generated by full_transaction_bytes.
        let literal = concat!(
            "0100",
            "0100000000000000",
            "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
            "01020304",
            "0200000000000000",
            "0142",
            "0102030405060708",
            "0102",
            "0100000000000000",
            "0102030405060708",
            "0102",
            "0200000000000000",
            "ac51",
            "01",
            "0304",
            "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
            "1112131415161718",
            "cccccccccccccccccccccccccccccccccccccccc",
            "2122232425262728",
            "0200000000000000",
            "ddee",
            "3132333435363738",
        );
        let bytes = full_transaction_bytes(&sample()).unwrap();
        assert_eq!(hex::encode(&bytes), literal);
        assert_eq!(bytes.len(), 183);
        // Independent Python hashlib.blake2b over the manually transcribed
        // literal, digest_size=32, key=b"TransactionHash"; no Rust encoder import.
        assert_eq!(
            full_transaction_hash(&sample()).unwrap().to_string(),
            "9436028cfaec1ab267c3f374461be610842e5dd89634e4769f886d2eac1814a9"
        );
        assert_eq!(
            full_transaction_hash(&sample()).unwrap(),
            hashing::tx::hash(&sample())
        );
    }

    #[test]
    fn full_hash_commits_fields_excluded_from_transaction_id() {
        let original = sample();
        let original_id = original.id();
        let original_hash = full_transaction_hash(&original).unwrap();
        for mutation in 0..3 {
            let mut changed = original.clone();
            match mutation {
                0 => changed.inputs[0].signature_script.push(0),
                1 => changed.inputs[0].compute_commit = ComputeBudget(u16::MAX).into(),
                _ => changed.set_storage_mass(0),
            }
            changed.finalize();
            assert_eq!(changed.id(), original_id);
            let manual = full_transaction_hash(&changed).unwrap();
            assert_eq!(manual, hashing::tx::hash(&changed));
            assert_ne!(manual, original_hash);
        }
    }

    #[test]
    fn zero_storage_mass_and_absent_covenant_are_serialized_explicitly() {
        let mut tx = sample();
        let populated = full_transaction_bytes(&tx).unwrap();
        tx.outputs[0].covenant = None;
        tx.set_storage_mass(0);
        tx.finalize();
        let bytes = full_transaction_bytes(&tx).unwrap();
        assert_eq!(populated.len() - bytes.len(), 34);
        assert_eq!(&bytes[bytes.len() - 8..], &[0; 8]);
        assert_eq!(full_transaction_hash(&tx).unwrap(), hashing::tx::hash(&tx));
    }

    #[test]
    fn malformed_compute_representation_and_unsupported_version_reject() {
        let mut tx = sample();
        tx.inputs[0].compute_commit = kaspa_consensus_core::mass::SigopCount(0).into();
        assert!(full_transaction_bytes(&tx).is_err());
        tx.version = 2;
        assert!(full_transaction_bytes(&tx).is_err());
        tx.version = 0;
        assert!(full_transaction_bytes(&tx).is_err());
    }

    #[test]
    fn empty_and_multiple_input_output_vectors_match_upstream() {
        let empty = Transaction::new(1, vec![], vec![], 0, Default::default(), 0, vec![]);
        assert_eq!(
            full_transaction_hash(&empty).unwrap(),
            hashing::tx::hash(&empty)
        );
        assert_eq!(full_transaction_bytes(&empty).unwrap().len(), 70);
        let mut tx = sample();
        tx.inputs.push(tx.inputs[0].clone());
        tx.outputs.push(TransactionOutput::new(
            u64::MAX,
            ScriptPublicKey::from_vec(0, vec![]),
        ));
        tx.finalize();
        assert_eq!(full_transaction_hash(&tx).unwrap(), hashing::tx::hash(&tx));
    }
}
